### ISSUE TITLE
Use Store Country for regional package exclusion

### ISSUE THREAD

**Issue by nhahtdh** [SteamDatabase/BrowserExtension#101]
Currently, the extension is using GeoIP country for regional package exclusion. While this works for most users, when a user is traveling, their GeoIP would not match the Steam Store Country. It's more accurate to use Steam Store Country instead.

**Comment by xPaw** [comment]
That page does not have access to your store country.

**Comment by nhahtdh** [comment]
Can't the extension do something about it?

The free package page is supposed to work for logged in user, it should already grab data from https://store.steampowered.com/dynamicstore/userdata/ for DLC detection. Can't it get the country from https://store.steampowered.com/account/ page?

Or perhaps it's a better idea to open an issue on SteamDB site to get store country when a user is logged into SteamDB, which then could be used by the extension to filter the packages?

**Comment by xPaw** [comment]
Not going to do that.
