### ISSUE TITLE
Cloudflare is challenging extension requests: Number of current players / date of last depot update / Lowest recorded price no longer shows

### ISSUE THREAD

**Issue by Tenome** [SteamDatabase/BrowserExtension#102]
Did Steam change some stuff under the hood? These no longer show for me.

https://puu.sh/IrFCX/728a0bda4b.png

**Comment by Citrinate** [comment]
Also started experiencing this.  The extension is sometimes being issued Cloudflare Captcha challenges in the background which can't be completed.

**Comment by Tenome** [comment]
It fixed itself for me, but since other people are having it, I'll leave it up. If it's captcha, then maybe me completing the captcha elsewhere fixed it.

**Comment by muhasturk** [comment]
it was not duplicate issue but anyway.

**Comment by xPaw** [comment]
It's the same root cause, the request to SteamDB gets challenged by Cloudflare. Visiting SteamDB and passing the challenge if any should (temporary) fix this.

Unfortunately I can't allow extension requests through the bot management.

**Comment by muhasturk** [comment]
thank you for detail explanation.

**Comment by xPaw** [comment]
Should no longer be an issue.
