### ISSUE TITLE
Current Best / Historical Low: Wrong game fetched

### ISSUE THREAD

**Issue by Xerono** [SteamDatabase/BrowserExtension#107]
"Current best: 3,29€ at Steam" on [the steam page for "OneShot"](https://store.steampowered.com/app/420530/OneShot/) - the "at Steam" links to [One Shot](https://store.steampowered.com/app/1221330/One_Shot/), which is not related to the game "OneShot".

"One Shot" costs 3,29€ currently, "OneShot" costs 6,99€. Looks like the extension pulls the "current best" from the wrong game. I assume it's the same for "Historical Low", since both games have the same "Historical Low" price at the same time .

**Comment by xPaw** [comment]
SteamDB doesn't use game names to pull prices, and "Current best: 3,29€ at Steam" is not the wording SteamDB extension uses.
