### ISSUE TITLE
Display subid names on Unknown package XXXX inventory gifts

### ISSUE THREAD

**Issue by nolddor** [SteamDatabase/BrowserExtension#117]
As gift collector, would be awesome to have  the subid 'Last Known Name' for those inventory gifts that have lost the name due to subid storage page been removed from Steam.

Here, a quick mockup:
![gift](https://i.imgur.com/Rkl50LD.png)

Kind Regards

**Comment by xPaw** [comment]
While technically possible, I don't want to add a request for this.

And now that we don't have package names for new packages that no one submits a Steam key for, SteamDB has no names, which would make this sub par.
