### ISSUE TITLE
No URLs on region-locked game page when going to its news

### ISSUE THREAD

**Issue by TotalCaesar659** [SteamDatabase/BrowserExtension#119]
When I go to region-locked game page ([example](https://store.steampowered.com/app/208140/)), both SteamDB and PCGamingWiki URLs are present:
![0](https://user-images.githubusercontent.com/14265316/188271876-6c1ddad1-4995-4919-b5d2-55404c18e1fe.jpg)
But when I go to any news URL of this game ([example](https://store.steampowered.com/news/app/208140/view/2909844527766025454)), they're gone:
![1](https://user-images.githubusercontent.com/14265316/188271879-d59f0955-53fd-402e-b52c-b05270082768.jpg)
It happens on both Chromium and Firefox with latest extension version.

**Comment by xPaw** [comment]
Sounds like the script needs to run on /news/app/ URL. Can you try testing same announcement but on the community domain?

**Comment by TotalCaesar659** [comment]
Well, here its direct URL in community (there are may be other URLs for it but I don't know them):
https://steamcommunity.com/games/endless-space/announcements/detail/1703951743101167654
It looks like this:
![2](https://user-images.githubusercontent.com/14265316/188273000-fabcb7b8-0890-4b2a-bb30-421cea7af1e5.jpg)
There are no any SteamDB elements (but I don't know they should be or not).

**Comment by TotalCaesar659** [comment]
Thanks, I've tested git build and it works.
