### ISSUE TITLE
Show SteamDB links on adult-restricted pages

### ISSUE THREAD

**Issue by nisehime** [SteamDatabase/BrowserExtension#121]
On age-restricted pages (adult only games which require login, [such as](https://store.steampowered.com/agecheck/app/644560/)) steamdb links are absent.

I found this [script](https://greasyfork.org/scripts/446021) which seems to be able to bypass those login requirements, but it's in chinese. Maybe you can take something from it to your extension and implement bypassing it too? (Looks like its just adding a few cookies though)

**Comment by xPaw** [comment]
There's already an option to skip agegate, is that not what you want?

**Comment by nisehime** [comment]
I'm talking about adult restricted (porn) games, which require to be logged in and have "show adult content" or something like that to be enabled (but in fact it looks like you just need to set two cookies). If your extension supposed to bypass it, it doesn't seem to work.

**Comment by nisehime** [comment]
Actually it works lol. The problem is that it's not triggered on the login-required agecheck page, only on the "enter your age" type.

**Comment by xPaw** [comment]
I fixed buttons to appear on /agecheck/app/ error pages.

> The problem is that it's not triggered on the login-required agecheck page, only on the "enter your age" type.

Seems like it does set the cookies, but you have to manually remove /agecheck/ from the url, because the script doesn't trigger because the page is saying an error. I don't want to change this to avoid possible infinite loops.

**Comment by nisehime** [comment]
>Seems like it does set the cookies, but you have to manually remove /agecheck/ from the url

You're right. That's a bit confusing. Maybe it'd be better if it had some kind of hint at least or like "try to bypass/try again" button.
