### ISSUE TITLE
[Feature] inject `cc` in ajax requests

### ISSUE THREAD

**Issue by nisehime** [SteamDatabase/BrowserExtension#122]
If you open any page with `cc=` parameter the dynamic requests made from this page won't be affected by it, which makes some things to not work as expected. For example: https://store.steampowered.com/publisher/squareenix/?cc=jp

Scroll to the bottom, the first games in "new releases" tab are loaded as expected for `cc=` set region, but now continue scrolling or switch to another tab (top sellers) or change filter settings and new items are loaded based on your actual IP region. The mini window which is shown when you hover mouse over games may also now work if it's region restricted game for the same reason.

The workaround to this is injecting `cc` param into those dynamic requests urls.

**Comment by xPaw** [comment]
This is on Valve to fix.

**Comment by nisehime** [comment]
Where do I report it?
