### ISSUE TITLE
Add the PC Gaming Wiki (PCGW) and SteamDB elements to the Steam mobile layout

### ISSUE THREAD

**Issue by 07416** [SteamDatabase/BrowserExtension#124]
Easy access to both PCGW and SteamDB directly from the Steam mobile website would be convenient. There may be space for the 'community hub' link (part of the original Steam desktop page layout) as well.

desktop: 

![image](https://user-images.githubusercontent.com/14923168/193130926-f28db613-4127-41f5-b1d8-ebd2260e84b5.png)

mobile: 

![Screenshot_20220929-225519_Fennec](https://user-images.githubusercontent.com/14923168/193129957-11b73b35-e4ab-4430-80bc-e4d4664d006c.png)

---

the said elements (icons) for clarity:

![image](https://user-images.githubusercontent.com/14923168/193131739-a5258188-1662-41b9-9e02-f1c5ed625ead.png)  
![image](https://user-images.githubusercontent.com/14923168/193131781-fd995038-155e-48a8-aaea-86026934d055.png)

**Comment by xPaw** [comment]
They're already there under links & info below.

**Comment by 07416** [comment]
> They're already there under links & info below.

I see, thank you for the reply. Perhaps a setting to match the desktop layout?

**Comment by xPaw** [comment]
Well there is no community hub button on mobile like on desktop, so I matched what Valve did.
