### ISSUE TITLE
Issue about translation

### ISSUE THREAD

**Issue by taozhiyu** [SteamDatabase/BrowserExtension#125]
Hi, I have just forked this repository and would like to submit a language adaptation pull request for Simplified Chinese (zh_CN).

However, I found that the github source code and the chrome app shop plugin version are the same, but the manifest version is different. Is it not synced to github? Or is it currently change and pull requests directly from the github version?

**Comment by xPaw** [comment]
It's pulled from manifest-v3 branch.

However the readme currently reads:
> Please do not make pull requests adding translations or languages at this time.
