### ISSUE TITLE
Import/Export Settings Buttons

### ISSUE THREAD

**Issue by ThomasHineXYZ** [SteamDatabase/BrowserExtension#132]
I like to sync my list of extensions and their accompanying settings information (JSON file or text data) using a git repo. 

Can we add a set of buttons to import and export settings for this extension? Whether copying and pasting text data or saving/loading a JSON file. Either one would be amazing.

The main issue that came to this thinking, was that Augmented Steam had the option to replace the `Install Steam` button with an `Open in Client` button. However, your extension had the `Hide "Install Steam" button in header ` option enabled by default. I admit it took me too long to think to check the SteamDB for this option, but it didn't dawn on me.

**Comment by xPaw** [comment]
Realistically it should use synced storage for settings: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

**Comment by guitaristtom** [comment]
@xPaw But what about browsers that aren't based on Firefox? Or if someone is using multiple browsers throughout the day?

**Comment by xPaw** [comment]
Firefox supports sync too. Manual export/import isn't worth the effort when all the settings boil down to just some checkboxes, it makes more sense when there's some custom stuff you can enter.

**Comment by louisgrasset** [comment]
Basically all major browsers supports a synced storage API.
Adding a way to import/export your settings could be useful, but it may not be worth implementing it as @xPaw said.

**Comment by xPaw** [comment]
The settings are stored in settings.sync for couple months now
