### ISSUE TITLE
[Feature Request] Sending Notifications for Free Apps

### ISSUE THREAD

**Issue by ramazansancar** [SteamDatabase/BrowserExtension#137]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Free games coming to https://steamdb.info/upcoming/free/ will check via background.js as long as my browser is open and send a notification if I haven't seen it before.

### Describe alternatives you've considered

For this purpose, an endpoint is created and the control is provided and notification is sent by sending a request at regular intervals.

**Comment by xPaw** [comment]
This is practically speaking outside of the scope of the extension. And require push infrastructure on the server (which would not require an extension).

Our Discord has a free promotions channel which can optionally ping you via a role.

**Comment by ramazansancar** [comment]
@xPaw By notification I mean sending a message to the browser. It can be done through this plugin. Thanks for the quick return. I wasn't expecting it so fast.

Check here:
- https://developer.chrome.com/docs/extensions/reference/notifications/

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Notifications
