### ISSUE TITLE
"Move game selection on inventory page to the side" doesn't seem to work

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/BrowserExtension#139]
### Describe the bug

![image](https://user-images.githubusercontent.com/30274161/234946635-aea6aa01-3fe6-4dc9-85fa-7d9698f1847b.png)

What is this option supposed to do? As I understand it, it should move the selection of game inventories to the left side of the screen instead of leaving them at the top (which is the Steam default).

But it doesn't seem to work.

### Browser name and version

Firefox 112.0.2 (64-bit)

**Comment by xPaw** [comment]
Works for me, is your window size big enough?

**Comment by xPaw** [comment]
It only works on big enough screens.
