### ISSUE TITLE
Set currency in options

### ISSUE THREAD

**Issue by ghost** [SteamDatabase/BrowserExtension#14]
I am missing the option to set a desired currency for the steamDB calculator website.

If i click on the SteamDB Icon which redirects me to the calculatori get redirected to:
`https://steamdb.info/calculator/76561198125362467/`
but i think it would be very helpful to set a desired currency that users can get redirected directly to the page they want:
`https://steamdb.info/calculator/76561198125362467/?cc=eu`

**Comment by xPaw** [comment]
If you change currency in any other part of the site, it will be stored in cookie, so when you visit calculator links, it will use that currency. I didn't do this on calculator pages specifically because users can link to it with `?cc` in the url.
