### ISSUE TITLE
More visible current lowest price on wishlist?

### ISSUE THREAD

**Issue by eaganlai** [SteamDatabase/BrowserExtension#140]
### Is your feature request related to a problem? Please describe.

I think it would be better to display the current lowest price across all site under the steam price, so that we can know the price without hovering.

Something like this:
![image](https://github.com/SteamDatabase/BrowserExtension/assets/74284983/deb5093f-5ef4-4ffa-8164-2db5e6e9a631)

**Comment by xPaw** [comment]
This isn't SteamDB's.
