### ISSUE TITLE
Has any way been found to make adding free packages work again?

### ISSUE THREAD

**Issue by Erfaniom** [SteamDatabase/BrowserExtension#141]
### Describe the bug

I'm really getting behind on the free packages (they have already reached 270!) and wanna if any way has been found to make it work, or do we just have to wait for valve. by the way if a work around has been found i do not care how complicated it is or how dangerous it is, tell me it

### Browser name and version

Opera GX core: 99.0.4788.86

**Comment by maggu2810** [comment]
3.6.8 is available for Chromium / Chrome based browsers.
The Firefox addon site still lists 3.6.7 as the most recent one https://addons.mozilla.org/en-US/firefox/addon/steam-database/

**Comment by xPaw** [comment]
It's awaiting review by Mozilla.
