### ISSUE TITLE
It crashes the browser when accessing the discarded steamdb tabs.

### ISSUE THREAD

**Issue by Mishasama** [SteamDatabase/BrowserExtension#143]
### Describe the bug

1. Open 2 new tabs
2. Accessing the https://steamdb.info/keys/ in the first tab
3. Submit some keys
4. Discard this tab and jump to the next tab
5. Accessing any other webpage (e.g. steam store)
6. Restart the browser and restore the session
7. Click the discarded steamdb tab
8. Crash

### Browser name and version

Google Chrome	115.0.5790.98

**Comment by xPaw** [comment]
If your browser crashes, that's not the extension's fault.
