### ISSUE TITLE
401 Unauthorized when adding free license

### ISSUE THREAD

**Issue by pinguluk** [SteamDatabase/BrowserExtension#145]
### Describe the bug

Tried to activate these packages
https://steamdb.info/freepackages/

![image](https://github.com/SteamDatabase/BrowserExtension/assets/16257821/a1c2257b-ece2-452b-87da-f2d048ffd953)

then I tried to add the games' licenses individually by clicking "Add free license", 
![image](https://github.com/SteamDatabase/BrowserExtension/assets/16257821/95d42908-4ec0-4424-a2ef-70a1d0da9527)

and I've inspected the network request and Steam responds with 401 Unauthorized
![image](https://github.com/SteamDatabase/BrowserExtension/assets/16257821/a7381e40-6d5d-40e8-b2bc-2f051a39ca5a)

### Browser name and version

Chrome 115.0.5790.110

**Comment by xPaw** [comment]
Click preview in the response, what does Steam  actually say?

**Comment by pinguluk** [comment]
> Click preview in the response, what does Steam actually say?

null

**Comment by xPaw** [comment]
Did you try re-logging into the store?

**Comment by pinguluk** [comment]
> Did you try re-logging into the store?

Yes, I've tried incognito too

**Comment by xPaw** [comment]
Do you see steamLoginSecure cookie sent in that request?

Try manually visiting https://checkout.steampowered.com/checkout/addfreelicense you should see your avatar top right because you're logged in.

**Comment by pinguluk** [comment]
> Do you see steamLoginSecure cookie sent in that request?
> 
> Try manually visiting https://checkout.steampowered.com/checkout/addfreelicense you should see your avatar top right because you're logged in.

Weird, yesterday didn't work and I've tried again just now and now it works. Maybe Steam did some changes or had some issues regarding claiming free licenses and they fixed in the meantime?

**Comment by xPaw** [comment]
What exactly did you do that fixed it?

**Comment by pinguluk** [comment]
> What exactly did you do that fixed it?

Absolutely nothing, just tried to claim the license(s) again and they worked without any erro.r

**Comment by xPaw** [comment]
If anyone else is having issues:

## What to try:
- Update the SteamDB extension to version 3.6.9.
- Relogin into the Steam store. 
- If family view is enabled, enter the PIN on the Steam store.
- Restart your browser.

## Debugging the extension requests:
- Go to chrome://extensions/
- Toggle developer mode on top right
- Click Inspect views service worker on steamdb
- Go to network tab
- Click add free license somewhere on steamdb
- There should be addfreelicense request in the list, if you click it it shows stuff
- Click on the request, then click 'Preview' tab, it should show what the Steam response was
