### ISSUE TITLE
Feature request: Sort by offers

### ISSUE THREAD

**Issue by XHXIAIEIN** [SteamDatabase/BrowserExtension#148]
### Is your feature request related to a problem? Please describe.

> url: https://store.steampowered.com/search/?specials=1&filter=weeklongdeals

When browsing the list of deals games, add an option to sort by offers

### Describe the solution you'd like

e.g.
```
GameA  -90%
GameB  -80%
GameC  -70%
```
This has nothing to do with their prices, just use offers as a reference.

### Note

It would be even better if it could support multi-condition sorting and filtering. For example, after sorting by offers, then sort by user reviews.

**Comment by xPaw** [comment]
Out of scope. Just use steamdb sales page.
