### ISSUE TITLE
Gifts have a "View on Steam Database" button that is always greyed out

### ISSUE THREAD

**Issue by KarlCastle** [SteamDatabase/BrowserExtension#15]
The button is created disabled and the segment of code that is intended to enable it has a bug that stops it from completing:

/gifts/undefined/validateunpack
Failed to load resource: the server responded with a status of 404 (Not Found)
inventory.js:316

I'm guessing the structure of the asset/item from CInventory changed so item.description.id is now item.assetid and PopulateActions in inventory.js hasn't been updated?

**Comment by xPaw** [comment]
Do you want to make a PR fixing this?

**Comment by KarlCastle** [comment]
Yes, I'm new to Git so I think I've clicked all the right buttons. Loading as an unpacked extension this PR has the button enable and when clicked takes me to the correct page.
