### ISSUE TITLE
PCGW and SteamDB buttons at the top of the page appear only a few pixels tall

### ISSUE THREAD

**Issue by hgdagon** [SteamDatabase/BrowserExtension#150]
### Describe the bug

I've tried reinstalling the extension, but the issue persists. Not specific  to any game page, happens on all of them

![sdbext](https://github.com/SteamDatabase/BrowserExtension/assets/15173076/8615d42f-7bd5-4c99-86a1-8e96c3f9b981)

### Browser name and version

Firefox Dev Edition 118.0b4

**Comment by xPaw** [comment]
Augmented steam breaks it
