### ISSUE TITLE
"Remove all link filter links" option does not work

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/BrowserExtension#156]
### Describe the bug

After recent updates to the extension, the option to remove linkfilters from Steam results in the link not redirecting as intended and makes the browser reopen the same current page in a new tab.

Disabling the option makes the problem no longer occur.

By the way, not exactly a problem, but taking advantage of the issue: I think the text "Remove all **linkfilter** links" (without space between "link" and "filter") is better for clarity (avoiding confusion).

### Browser name and version

Firefox 119.0.1 (64-bit)

**Comment by xPaw** [comment]
This was fixed, make sure you update the addon.
