### ISSUE TITLE
An option to convert MENA/LATAM USD prices to the local currency

### ISSUE THREAD

**Issue by furkaneroi** [SteamDatabase/BrowserExtension#161]
### Is your feature request related to a problem? Please describe.

Now people who lost their currency on Steam have to do some math before buying games and I couldn't find this feature in other Steam extensions.

### Describe the solution you'd like

Maybe it can convert on mouseover

**Comment by xPaw** [comment]
This is better served by extensions such as Steamcito, perhaps they can expand to support other countries besides Argentina.
