### ISSUE TITLE
Extension Hides Owned Games Without Filtering on Sales Page

### ISSUE THREAD

**Issue by muhasturk** [SteamDatabase/BrowserExtension#162]
### Describe the bug

When SteamDB extension installed and enabled with default options, sales page filters or changes order owned games if I logged in steamdb webpage even appling no any steamdb filter.

### Owned Games are Filtered or Not on the first page
<img width="1007" alt="image" src="https://github.com/SteamDatabase/BrowserExtension/assets/4077401/8d8ded22-15c2-43ea-93ef-b091e1bfeef1">

### Owned Games are on the first page
<img width="1020" alt="image" src="https://github.com/SteamDatabase/BrowserExtension/assets/4077401/bd9bb9e2-d075-41db-b413-e83e8d328f72">

🔍 Do you have any idea for this behavior?

#### Environment:
Edition	Windows 11 Pro
Version	23H2
OS build	22631.2715

### Browser name and version

Microsoft Edge - Version 119.0.2151.72 (Official build) (64-bit)

**Comment by xPaw** [comment]
Owned games are deprioritized, wishlisted games are prioritized, this is intentional.

**Comment by muhasturk** [comment]
Is disabling the extension the only option if user wants to prioritized owned games?

**Comment by xPaw** [comment]
If you want to view your own owned games, just use the specific filter for them: https://steamdb.info/sales/?displayOnly=OwnedGames
