### ISSUE TITLE
Some apps aren't highlighted as owned games

### ISSUE THREAD

**Issue by TempleOfHorus** [SteamDatabase/BrowserExtension#163]
### Describe the bug

![1](https://github.com/SteamDatabase/BrowserExtension/assets/60355056/b31d8e1e-3987-41f9-b524-126fb5ed5bed)
![2](https://github.com/SteamDatabase/BrowserExtension/assets/60355056/2bb2be5d-57e8-44b3-9d32-10904063a906)

### Browser name and version

Firefox, version: 120.0

**Comment by xPaw** [comment]
This on Steam's end, I noticed this yesterday too that some apps were missing from https://store.steampowered.com/dynamicstore/userdata/
