### ISSUE TITLE
Possible redundant permission

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/BrowserExtension#168]
### Describe the bug

![image](https://github.com/SteamDatabase/BrowserExtension/assets/30274161/c72bbad0-41f3-42c6-b361-ad6e03d9a115)

### Browser name and version

Firefox 125.0.2 (64-bit)

**Comment by xPaw** [comment]
This is an issue with Firefox, it shouldn't show separate toggles when there is a wildcard one already. You can check the manifest
