### ISSUE TITLE
Extension error: Failed to load your games. NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by terrok9** [SteamDatabase/BrowserExtension#169]
- _Browser name and version:_ Firefox Developer Edition 127.0.0.8899
- _Device (mobile or desktop):_ Desktop
- _Page where the issue happens:_  Main page https://steamdb.info/

### Describe the bug
Browser response after and before logging in
![imagen](https://github.com/SteamDatabase/steamdb.info-issues/assets/67476075/e0d89dcf-04db-4287-b72c-5a472ecfd939)
Extensions in my current session
![imagen](https://github.com/SteamDatabase/steamdb.info-issues/assets/67476075/c6e1dc52-9583-4be5-a99f-77aa72a007e7)
Some console information
![imagen](https://github.com/SteamDatabase/steamdb.info-issues/assets/67476075/0bc96f53-f7ac-4e66-8c8e-89f6869b235b)

When I try to use steamdb extension in a Firefox Developer Edition Browser, it presents Extension Error on SteamDB's main page, I am not using Firefox containers and this also happens in private tabs.

If you need some information, I am glad to share more details. I am also trying to troubleshoot it.

**Comment by xPaw** [comment]
This is almost universally attributed to bad settings or extensions for Firefox users. Something is blocking the network request to Steam store in your browser. There's nothing to be fixed in the extension.
