### ISSUE TITLE
Bypass: Community content for this product may not be appropriate for all ages, or may not be appropriate for viewing at work.

### ISSUE THREAD

**Issue by Rik67** [SteamDatabase/BrowserExtension#17]
It would be nice to have an option that automatically bypasses this.

**Comment by SuperSandro2000** [comment]
This extension has this already: https://www.enhancedsteam.com/.
I don't think this fits into SteamDB.

**Comment by Lenmaer** [comment]
I tried that extension you linked.
How to say... 
It's a big fuck up. After 2 hours of use, Firefox was eating 18Gb of ram on the Steam tab.
Also I was asking for this function to be added because you already have an Age Check bypass option, so I thought an Adult Check bypass could be added too.

**Comment by SuperSandro2000** [comment]
Didn't know about the age check bypass.
It is probably your fault that Enhanced Steam does bad things. I use it in Chrome for years and never had such problems. But this goes OT.

**Comment by Revadike** [comment]
Use Augmented Steam instead, the successor of Enhanced Steam.

**Comment by xPaw** [comment]
Age gate on community page is done in some weird ways, I tried to do it the best way I could.
