### ISSUE TITLE
Change color of player stats icon

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/BrowserExtension#170]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/SteamDatabase/BrowserExtension/assets/30274161/ed396e17-4725-422a-852f-028500de9632)

On mouse-hover, the SteamDB icon turns white.
If hovered on the icon itself, a chrome tooltip is displayed:

![image](https://github.com/SteamDatabase/BrowserExtension/assets/30274161/85da0643-6530-4480-8d73-b6a2b7be69fd)

### Describe the solution you'd like

I would like for the icon to always be white instead of changing the color only on mouse-hover.

### Describe alternatives you've considered

Not exactly an alternative, but the icon turns white if hovered anywhere on the player stats box. If this suggestion is declined, then it would be nice to only change color when hovering over the icon itself rather than the entire box.

**Comment by xPaw** [comment]
It's fine as it is.
