### ISSUE TITLE
Remove analytics/telemetry/tracking from extension-added links

### ISSUE THREAD

**Issue by Tiagoquix** [SteamDatabase/BrowserExtension#171]
### Is your feature request related to a problem? Please describe.

Various links added by the extension have some kind of analytics/telemetry/tracking parameters.

Examples:

pcgamingwiki.com/api/appid.php?appid=252490 (actual link)
**&utm_source=Steam&utm_medium=Steam&utm_campaign=SteamDB%20Extension** (added telemetry)

steamdb.info/app/252490/charts/ (actual link)
**?utm_source=Steam&utm_medium=Steam&utm_campaign=SteamDB%20Extension** (added telemetry)

### Describe the solution you'd like

Remove all analytics/telemetry/tracking from extension-added links.

These are not necessary for the extension to function correctly and can be removed.
Furthermore, it is possible to bypass such telemetry entirely using lists in uBlock Origin.

I don't know if the extension itself has any type of telemetry (besides what it adds in links). If there is, it would also be interesting to remove it or have some way to disable it.

### Describe alternatives you've considered

Add a toggle to opt-in/opt-out, then:

- Require all analytics/telemetry/tracking to be opt-in by default (user consent). Asking the user to opt-in after installing is fine, as long as it does not turn itself ON without the user's explicit consent.
- Keep it as opt-out, but inform the user it is turned ON after installing the extension.

**Comment by xPaw** [comment]
These parameters are static and do not uniquely identify you, you can strip the parameters with ublock as you said if you really want to.
