### ISSUE TITLE
Option to see steam deck verification

### ISSUE THREAD

**Issue by nuciforan0** [SteamDatabase/BrowserExtension#175]
### Is your feature request related to a problem? Please describe.

Just wanna be able to see valve's verification for steam deck to see on the web if it is playable on it, would be nice.

### Describe the solution you'd like

Just some verification image of verified/playable/etc would be nice. 
Also would be nice if it links to the game's protondb page, but that isn't valve/steam oriented so makes sense if you guys don't end up doing this.

**Comment by xPaw** [comment]
Steam already shows that in the sidebar

**Comment by nuciforan0** [comment]
I don’t see it anywhere?
I am talking about store pages of games, like this https://store.steampowered.com/app/504230/Celeste/

**Comment by nuciforan0** [comment]
***@***.***

Same as on chrome/edge/firefox and if I’m logged in or not, maybe it’s a me problem though.

________________________________
