### ISSUE TITLE
[Question] How to get description of hidden achievements through steam web api?

### ISSUE THREAD

**Issue by tipsypotato** [SteamDatabase/BrowserExtension#179]
### Describe the bug

I'm wondering how to get description of hidden achievements through steam web api and found the code below, but it seems 'IPlayerService/GetGameAchievements/v1' doesn't exist in [Steamworks Documentation](https://partner.steamgames.com/doc/webapi/IPlayerService), so how do I get them?

https://github.com/SteamDatabase/BrowserExtension/blob/b3e81f043a56d2c263344caeb36caef3f2aefd8e/scripts/community/achievements.js#L148

Thank you in advance!

### Browser name and version

Chrome latest

**Comment by xPaw** [comment]
Well, the api clearly exists.

**Comment by tipsypotato** [comment]
nvm just found it [here](https://steamapi.xpaw.me/#IPlayerService/GetGameAchievements)
