### ISSUE TITLE
Games with old achievements layout breaks the new achievements script

### ISSUE THREAD

**Issue by Californ1a** [SteamDatabase/BrowserExtension#180]
### Describe the bug

https://github.com/SteamDatabase/BrowserExtension/blob/43ab01d0d749558690c8f67cfe2b639c77fc73db/scripts/community/achievements.js#L34

This selector doesn't exist if the page uses the old layout for achievements, like this one:
https://steamcommunity.com/id/Californ1a/stats/PuzzleAgent2/?tab=achievements

Not sure how many other games still use this layout; this is the only one I've come across. It might not even be worth the effort to fix if it's only a couple games affected.

### Browser name and version

Chrome latest

**Comment by xPaw** [comment]
It's not broken, it's being skipped. All these games have different layouts to
I didn't want to support.
