### ISSUE TITLE
Curator review not showing up.

### ISSUE THREAD

**Issue by DogancanYr** [SteamDatabase/BrowserExtension#185]
### Describe the bug

When I go to steam with the store button from steamdb, the curator review appears, but not when the steamdb plugin is open.
![Ekran görüntüsü 2024-07-03 172406](https://github.com/SteamDatabase/BrowserExtension/assets/90002969/1e68e38f-038e-4640-8d7f-3f3e81af5f27)

### Browser name and version

Firefox Latest

**Comment by xPaw** [comment]
That's intentional.

**Comment by DogancanYr** [comment]
Why ?
And is it written somewhere?
