### ISSUE TITLE
Suggest a token dump after Steam key activation containing new tokens

### ISSUE THREAD

**Issue by enchained** [SteamDatabase/BrowserExtension#186]
### Is your feature request related to a problem? Please describe.

After activating a key on Steam website, there is a SteamDB link added by the extension. If I follow it, sometimes there is "We have no information about this package" which might be a hint that I need to do a token dump.

But most people don't follow the link, and even if they do, they might not know they can contribute this token based on that page info.

### Describe the solution you'd like

Suggestions:
* Add a link to "Dump this token so SteamDB knows more about it" to the unknown subs on the post-activation page of https://store.steampowered.com/account/registerkey.
* Add a token dumping prompt on the SteamDB page to the "We have no information about this package" banner if extension marked sub as owned.

This way people can see right away they have something useful to dump.

Also, looks like sub names are not available even after token dumping? Maybe an opt-in option to send the post-activation sub name to SteamDB could also be helpful.

**Comment by xPaw** [comment]
I don't want to add a generic message to extension to say dump tokens (it won't know if site needs a token dump without sending the subid to the site either, so it would be generic).

> Maybe an opt-in option to send the post-activation sub name to SteamDB could also be helpful.

Such an api would be abusable, the way to do this is to submit the same key to https://steamdb.info/keys/
