### ISSUE TITLE
Option to display prices with tax

### ISSUE THREAD

**Issue by Chew** [SteamDatabase/BrowserExtension#187]
### Is your feature request related to a problem? Please describe.

Hi Europeans, you lucky you, you already have this! Sadly, the United States tax laws only require the price to include tax for airline tickets. Since Steam games do not fall under this category, prices shown on Steam are pre-tax. This causes issues like "Under $10" showing games priced initially at $9.99, but ending up costing about $10.81

![CleanShot 2024-07-10 at 23 51 14](https://github.com/SteamDatabase/BrowserExtension/assets/8278263/de9f60fd-798c-4cd4-ab5c-d9c82a3d6c8d)

### Describe the solution you'd like

It would be nice to have an option to enter what the tax % would be in our jurisdiction and then start seeing how much I'd actually be paying.

### Describe alternatives you've considered

Hoping I have enough money, or being able to add 8% to a price in my head.

**Comment by xPaw** [comment]
Realistically not gonna happen in this extension, this would involve a lot of work. If someone really wanted to, this would warrant making a standalone extension.
