### ISSUE TITLE
Request to add the 'Open in new window' feature! (attached photo!!!)

### ISSUE THREAD

**Issue by coreVoid** [SteamDatabase/BrowserExtension#196]
### Is your feature request related to a problem? Please describe.

The areas where new features will be added are marked with green boxes, text, and arrows.

![68747470733a2f2f737465616d64622e696](https://github.com/user-attachments/assets/c146b9e4-52fa-4721-a3c0-39a990d9e166)

Please add the 'Open in new window' feature to the link as shown in the attached photo.

**Comment by xPaw** [comment]
Middle click or hold ctrl.
