### ISSUE TITLE
MSEdge : Extension is broken and needs to be reinstalled

### ISSUE THREAD

**Issue by mariothiel** [SteamDatabase/BrowserExtension#2]
After i install the extension and restart Edge, i get prompted that the extension is broken and needs to be reinstalled. Doing that doesn't solve the problem though. I am on the latest Insider Build of Windows and Edge.

**Comment by Gabsletobar** [comment]
I have the same issue and i have a "regular version (not Insider)" of the Windows.

**Comment by xPaw** [comment]
The most likely explanation here is that Microsoft disables all loaded extensions on restart. And we are not able to publish our extension to the MS store 🤷‍♂️

**Comment by xPaw** [comment]
I have no plans to publish for Edge, as Microsoft will be moving to Chromium.
