### ISSUE TITLE
Add SteamDB button to steam store search queries

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#20]
Examples:

- https://store.steampowered.com/search/?publisher=ArcaneRaise would link to https://steamdb.info/search/?a=app_keynames&keyname=241&operator=3&keyvalue=ArcaneRaise

- https://store.steampowered.com/search/?term=grand%20theft%20auto would link to https://steamdb.info/search/?a=app&q=grand%2520theft%2520auto&type=-1&category=0

- https://store.steampowered.com/search/?filter=comingsoon would link to https://steamdb.info/upcoming/

Et cetera

**Comment by Revadike** [comment]
I have an idea: instead of adding steamdb buttons to relevant pages in custom locations, why not have a `position: fixed;`-botton (bottom right for example) where not only you can go to steamdb's equivalent page, but also to steam client's equivalent's page, much like [this userscript](https://gist.github.com/promythyus/977d3d7c8343463d4861) does, but more extensive using all of the [Steam Browser Protocols](https://developer.valvesoftware.com/wiki/Steam_browser_protocol). What do you think of this?

**Comment by xPaw** [comment]
Gonna close this as I have no plans to add this.
