### ISSUE TITLE
Extension not being recognized in Sales page on Firefox

### ISSUE THREAD

**Issue by cbornhoft** [SteamDatabase/BrowserExtension#208]
### Describe the bug

Video attached to show what I'm seeing. Let me know if you need anymore info!

[steamdb.webm](https://github.com/user-attachments/assets/fd91f476-2da1-4213-a29c-fe85ab0b2769)

### Browser name and version

Firefox 133.0.3

**Comment by xPaw** [comment]
Privacy options or containers screw with it, or you're not logged into the store. There is a popup when it fails to load data which you likely closed.

**Comment by cbornhoft** [comment]
Hey @xPaw, I've confirmed I'm logged into the store on the same Gaming container. No popup appeared, all data appears on my account correctly.

I'll try without a container and see if that resolves it.

**Comment by xPaw** [comment]
#56.
