### ISSUE TITLE
ERROR! Firefox v61

### ISSUE THREAD

**Issue by Areopagit** [SteamDatabase/BrowserExtension#21]
ERROR!
The add-on downloaded from this site can not be installed, as it seems to be corrupted.

Please correct!
Firefox v61.

**Comment by xPaw** [comment]
Works for me.

Contact Mozilla if you're having issues downloading the addon, as I haven't touched it in months.

**Comment by Areopagit** [comment]
Firefox Update to v61. And extention dont work!

Extention working on Firefox v60.

**Comment by xPaw** [comment]
Cool, complain to Mozilla.

**Comment by Areopagit** [comment]
:( Too bad.

**Comment by Areopagit** [comment]
This problem was on 2 PC (work/home).
Reinstall FF fix problem.
Thanks!
