### ISSUE TITLE
Possible for Safari on macOS?

### ISSUE THREAD

**Issue by zanderzhng** [SteamDatabase/BrowserExtension#22]

**Comment by xPaw** [comment]
No. Publishing for Safari is a major pain in the ass and requires an Apple device.

**Comment by iMonZ** [comment]
> No. Publishing for Safari is a major pain in the ass and requires an Apple device.

No it doesn’t

**Comment by xPaw** [comment]
Ye well, I'm still not going to publish it for Safari.

**Comment by iMonZ** [comment]
> Ye well, I'm still not going to publish it for Safari.

Safari support Firefox extensions and you don’t have to own an mac

**Comment by iMonZ** [comment]
I can make an PR with all the missing files that it needs to have

**Comment by xPaw** [comment]
Thanks for the offer, but I have no desire to deal with Apple's ecosystem.

**Comment by iMonZ** [comment]
> Thanks for the offer, but I have no desire to deal with Apple's ecosystem.

You don’t have too.
I can do everything.
I think I can create a PR this week

**Comment by xPaw** [comment]
Please don't.
