### ISSUE TITLE
"Show Wishlisted Only" Greyed Out

### ISSUE THREAD

**Issue by ourichermath** [SteamDatabase/BrowserExtension#23]
On the steamdb.info page for current Steam sales:

https://steamdb.info/sales/

the "Show Wishlisted Only" option is grayed out.  If I hover over it, it shows a red, crossed circle symbol (i.e., "not") and says "Requires Browser Extension."  According to my Chrome Extensions list, I'm running version 1.8.3 of the Steam Database extension.  According to the extension's options, I've got the "Highlight owned and wished products on steamdb.info" option turned on and I've added "store.steampowered.com" to Chrome's cookie whitelist.

I'm on:
- Microsoft Windows 10 Pro (x64)
- Chrome Version 69.0.3497.23 (Official Build) beta (64-bit)
- Steam Database extension version 1.8.3

**Comment by xPaw** [comment]
Are you logged in on the steam store? Try force refreshing (also clear localStorage on steamdb.info)

Check console for any errors.

**Comment by ourichermath** [comment]
I wasn't logged in to the actual Steam store.  I assumed access to my Wishlist would have been handled by my being logged in to Steam on the steamdb.info site.  Once I logged in directly to the Steam store, that option opened up.  Thanks.

Note:  in the Steam Database options, the note near the bottom explaining that whitelisting store.steampowered.com should probably be expanded to say that we have to be signed into the actual store in the browser.
