### ISSUE TITLE
Chrome store links are invalid

### ISSUE THREAD

**Issue by ChildishGiant** [SteamDatabase/BrowserExtension#26]
The link given on both https://steamdb.info/extension/ and [README.md](https://github.com/SteamDatabase/BrowserExtension/blob/c73bc7f72d2e7fdffa4e5810c9d0e6d2c9d4ae2a/README.md) (https://chrome.google.com/webstore/detail/kdbmhfkmnlmbkgbabkdealhhbfhlmmon) is returning as a 404 error for me.

![image](https://user-images.githubusercontent.com/13716824/44882876-1d8e8800-acad-11e8-85d3-4bc85dd1ceed.png)

**Comment by xPaw** [comment]
Welp, it got taken down for some reason. We didn't get any email about this.

**Comment by ChildishGiant** [comment]
🤔 Could you put a .crx up on the repo's releases while you contest the takedown or whatever the next step is?

**Comment by xPaw** [comment]
You can simply download the repo and load it in Chrome.

**Comment by xPaw** [comment]
It's back.
