### ISSUE TITLE
browser extension shows me UAH instead of RUR can we have a setting to select a currency?

### ISSUE THREAD

**Issue by ndandy** [SteamDatabase/BrowserExtension#28]
browser extension shows me UAH instead of RUR in "lowest recorded price" can we have a setting to select a currency in a browser extension?

**Comment by xPaw** [comment]
Extension uses the country that you have already set by Steam in cookies.

Does Steam detect you as being in Ukraine or something? What prices does it show you?

**Comment by xPaw** [comment]
I deployed a change on the server, can you tell me if this still happens to you? It should be using currency first to find correct price now.

**Comment by ndandy** [comment]
now it's great :) 
thank you a lot!

**Comment by xPaw** [comment]
Great!
