### ISSUE TITLE
Display Steam Card Exchange link

### ISSUE THREAD

**Issue by ZSkycat** [SteamDatabase/BrowserExtension#29]
> image from Enhanced Steam

**profiles badges page**
![image](https://user-images.githubusercontent.com/20368649/48568038-76c79880-e939-11e8-89eb-4e5cda4a9f51.png)

**profiles gamecards page**
![image](https://user-images.githubusercontent.com/20368649/48568038-76c79880-e939-11e8-89eb-4e5cda4a9f51.png)

**Steam store pages**

😄 I hope `Steam Database Extension` can replace `Enhanced Steam`. And more convenient

**Comment by xPaw** [comment]
What is it useful for?

Currently I have an opinion of not adding other websites to the extension (looking at ES there's so many different service links that I certainly wouldn't want to add)

**Comment by ZSkycat** [comment]
View all badges, cards, and backgrounds about game.

Example: https://www.steamcardexchange.net/index.php?gamepage-appid-292030

I respect your opinion. From the standpoint of steamdb, there is no problem with this.

Enhanced Steam is end of life. Maybe I should make this feature a separate oil user script. 😅 
http://www.enhancedsteam.com/blog/?p=256

**Comment by KarlCastle** [comment]
[Gist of a user script that duplicates Enhanced Steam's functionality.](https://gist.github.com/KarlCastle/c10d1f57746e2656d04ac0fa45ca0f82)

**Comment by xPaw** [comment]
Augmented Steam has this.
