### ISSUE TITLE
Online stats doesn't work in Firefox

### ISSUE THREAD

**Issue by Keith94** [SteamDatabase/BrowserExtension#3]
On all Steam pages (e.g. Grand Theft Auto V) the online stats is displayed as N/A

![firefox_2017-02-19_18-27-16](https://cloud.githubusercontent.com/assets/5490615/23109855/75c2c4a2-f6d1-11e6-92f6-954e1edefc7b.png)

But on actual SteamDB page it looks okay

![firefox_2017-02-19_18-28-26](https://cloud.githubusercontent.com/assets/5490615/23109859/7dfda38a-f6d1-11e6-83d3-5e1317d495da.png)

**Comment by xPaw** [comment]
Will be fixed in WebExtensions version (1.7.1).
