### ISSUE TITLE
about cheat the queue

### ISSUE THREAD

**Issue by ZSkycat** [SteamDatabase/BrowserExtension#30]
[Related code](https://github.com/SteamDatabase/BrowserExtension/blob/0a2829e415599c99d508dd7ea5767f2159959806/scripts/store/explore_injected.js)

## Not stated in the [feature list](https://steamdb.info/extension/)
Desired behavior:
![image](https://user-images.githubusercontent.com/20368649/50377898-b718e580-0660-11e9-8413-bb2943eab914.png)

## Can not be disabled in extension options
Desired behavior:
![image](https://user-images.githubusercontent.com/20368649/50377936-9ef59600-0661-11e9-88fa-1ca75095370a.png)

### Can not recognize the completed explore queue. ([Better implementation](https://steamcn.com/t157861-1-1))
Desired behavior:
When my explore queue was manually done a part. It does not automatically explore queues without card.

**Comment by xPaw** [comment]
What is the issue you are reporting here?

**Comment by ZSkycat** [comment]
@xPaw I don't know its English is called 'explore queue' or'discovery queue'. I updated the content.

**Comment by xPaw** [comment]
> Not stated in the feature list

I added it

> Can not be disabled in extension options

There's no real need for it

> When my explore queue was manually done a part. It does not automatically explore queues without card.

And? It restarts the queue and does 3 queues, you still get 3 cards regardless if you already had a queue or not.

**Comment by ZSkycat** [comment]
I suggest making it smarter. Instead of a fixed does 3 queues. Of course, the current logic is no problem.

**Comment by xPaw** [comment]
There's no reason to make it 'smarter' besides making the code more complicated.
