### ISSUE TITLE
Add OpenCritic score to store pages

### ISSUE THREAD

**Issue by Floyd77** [SteamDatabase/BrowserExtension#31]
Enhanced Steam has this feature but they announced [EOL](http://www.enhancedsteam.com/blog/?p=256) on past July. It could be a very good enhancement for SteamDB extension. Thanks.

![](https://imgur.com/5dMwMUc.png)

**Comment by Revadike** [comment]
Checkout (Augmented Steam](https://es.isthereanydeal.com/), it is a continuation of Enhanced Steam!

**Comment by xPaw** [comment]
Augmented Steam has this.
