### ISSUE TITLE
Please Reconsider the Position of new Sub Information within Steam Store Pages

### ISSUE THREAD

**Issue by Black3ird** [SteamDatabase/BrowserExtension#35]
Dear Sir,

Had been using SteamDB Extension (Chrome) for years and thank you for your hard work as it's now a "Must Install" extension along uBlock Origin and Augmented Steam along few others that eases user's life quite much.

But, since the Last Update on your Extension, while other new features added or improved, noticed that you choose to **move** the Steam Sub information per Game Page from [here](https://pbs.twimg.com/media/Dr-glVCU4AIwZw1.jpg) to new location of [there](https://imgur.com/a/pboyn7g) while at first I thought myself as it got better attention due _"Contrast"_ both in color and positioning of the Link, last image _proves_ that such positioning is quite unfortunate and **breaks** page fluidity and design.

Last image is taken as of now (erasing personals) as it is the result of both Augmented Steam (on Price for 8 countries Always On for comparison) and SteamDB installed. As you can see due to Augmented Steam's "Show Package Info for All Apps" setting turned on, there are **two packages** present for the game Subs 46002 and 46736 which creates two blue-ish buttons (normally there's only One Sub) which squeezes the new position of your Sub Information more as if itself already wasn't squeezing the "X Friends want this game" info line down below.

Considering Augmented (Enhanced) Steam features that seems to cause trouble **had been there for years** before such change of SteamDB itself, sadly it's SteamDB's _new choice_ of location for Sub Information that's causing the problem, not AS at all. It both lacks the _"Other"_ sub's information AS provides and **wedges** itself between Steam > AS prepared Page Layout for worse viewing pleasure. Also your new location _Shifts_ AS's blue buttons and Steam's Price Information so that it overlaps with the "Price per Country" Info Box making Price information to be Half-Seen.

If it was Augmented Steam to get newer change that causes such disruption, I would have posted it on https://github.com/tfedor/AugmentedSteam/issues instead of here yet since your change is the Last one, I'm believing it's also your responsibility to remedy the situation for your User's ease as there was nothing wrong with the _"Previous Location"_ of Sub Information as presented in the **first** image linked above.

You could suggest to turn off Augmented Steam's feature yet it's both an unnecessary suggestion and not-an-alternative one because SteamDB links Sub Information to SteamDB Site itself whereas Augmented Steam links Sub Information to **within** Steam Sub pages such as https://store.steampowered.com/sub/46736/ which is also missing from your extension. So as a Power User having access to both functionality is more important instead of having to have close things for **Identical Functionality** such as both AS and you're offering Player Stats while AS place is on bottom and you put in Sidebar where I have one of them turned off for same stats.

Sorry for long read and finally, please _reconsider_ the positioning of your **New** Sub information maybe to the old place but with new look and colors so that pages and extensions can co-exist in harmony instead of pushing one another within page. I can rectify the situation for only myself and had been using Stylus+UserStyles for quite some time with CSS information so that I can write myself a **Custom CSS** to fix your new choice for such information to its old place but this won't be the option for many other users that is using your Extension.

For their sakes please take this into consideration.

Best Regards.

**Comment by xPaw** [comment]
Looking at your screenshots, it looks broken for you because you have duplicate "Package info" buttons for whatever reason.

I just installed Augmented Steam and it looks completely fine for me.

You can also disable "Display SubID under each purchase option" option in SteamDB.
