### ISSUE TITLE
Add isthereanydeal.com

### ISSUE THREAD

**Issue by 07416** [SteamDatabase/BrowserExtension#36]
https://isthereanydeal.com/

I recommend displaying next to the PC Gaming Wiki and SteamDB icons on the game pages (the upper right corner).

![2019-06-26 12_02_42-Window](https://user-images.githubusercontent.com/14923168/60166724-5aaea280-980a-11e9-8e38-6ef9175f2bd5.png)

**Comment by xPaw** [comment]
They have their own extension already.

**Comment by 07416** [comment]
> 
> 
> They have their own extension already.

I'm not asking for pulling any data from the website, only linking to their respective pages as you do with PC Gaming Wiki.
