### ISSUE TITLE
Get Free Licenses button

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#37]
![image](https://user-images.githubusercontent.com/4411977/62946016-2a35be80-bde0-11e9-9137-4a46a59287f3.png)

On your licenses page. This would make it more convenient for people. They wouldn't have to copy the script, then go to the license page, open dev tools to run it. Instead, it will be a simple button click.

**Comment by Revadike** [comment]
I'd make a pull request myself, but I kinda need an API for this. I wouldn't want to scrape the page.

**Comment by xPaw** [comment]
There's enough effort for little gain adding this, especially with rate limits. It's just a support nightmare as people don't fully understand what it does.

**Comment by Revadike** [comment]
What do you mean?

**Comment by arseny92** [comment]
Maybe better as a configurable option (disabled by default) that users could enable if needed in extension options? Otherwise `enough effort for little gain` and `people don't fully understand what it does` may as well be argued about half of the settings of the extension.
