### ISSUE TITLE
Display badge position on profile

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#38]
![image](https://user-images.githubusercontent.com/4411977/62946188-87ca0b00-bde0-11e9-874b-b1c5d809c929.png)

It would be cool if the top game owner and top level owners position could get displayed on the respective steam profiles.

**Comment by Revadike** [comment]
I'd make a pull request myself, but I kinda need an API for this. I wouldn't want to scrape the page.

**Comment by xPaw** [comment]
This would require polling an API for each profile you visit, I don't want to do that. Same applies to #39

**Comment by Revadike** [comment]
Ever heard of cache? Just get the entire top 500 list and keep it for 24h or something? :S

**Comment by xPaw** [comment]
I don't want to do that.
