### ISSUE TITLE
Delete/restore packages

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#40]
Add a button or link where we can delete (later restore) owned steam packages. This is done via help.steampowered.com API. All "permanently" removed packages, can be restored from my experience, even when you might expect AlreadyOwned error.

**Comment by xPaw** [comment]
I'd rather not features that "abuse" the support system.

**Comment by Revadike** [comment]
Well, there are valid use cases, like the support page not being able to load, but I see your point.
