### ISSUE TITLE
Allow sending steam gifts to friends who already own it

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#41]
This is a UI restriction and it works just fine if you enable the checkboxes. I think Valve only put this in, because they didn't think people would want to send gifts to others that already own it.

**Comment by xPaw** [comment]
Are you sure it actually works without restrictions?

**Comment by Revadike** [comment]
> Are you sure it actually works without restrictions?

We recently tested it. It works if you already have the gift in your own steam inventory. It doesn't work if it is a new game you wanna purchase as gift.

**Comment by xPaw** [comment]
I guess we could unlock the radio button so it's selectable but still keep the already owns text.

Want to make a PR?

**Comment by Revadike** [comment]
> I guess we could unlock the radio button so it's selectable but still keep the already owns text.
> 
> Want to make a PR?

Sure
