### ISSUE TITLE
Add-on causes "Install Steam" download button to be removed on Firefox 69

### ISSUE THREAD

**Issue by user00101010** [SteamDatabase/BrowserExtension#44]
Hello everyone!

I noticed the extension removes the "Install Steam" download button, which is normally located left of the log-in buttons on top. I am running the latest Firefox 69.0 and haven't tested on other browsers. Disabling the extension and refreshing the page immediately resolves the issue. Expected behavior is obviously the button staying there.

Thank you.

**Comment by SuperSandro2000** [comment]
This is an intended feature and can be configured in the extensions options.

**Comment by user00101010** [comment]
Thank you very much for the quick answer. I actually read through the "button and links" section and scanned for "download" so I missed it, sorry. Nice feature actually 👍
