### ISSUE TITLE
Page to install the steamdb extension uses the old edge logo

### ISSUE THREAD

**Issue by rogersachan** [SteamDatabase/BrowserExtension#48]
https://steamdb.info/extension/

the new black and white art looks like this
![image](https://user-images.githubusercontent.com/7173984/68417155-dda21b00-0163-11ea-9f4c-070f38250402.png)

![image](https://user-images.githubusercontent.com/7173984/68429210-accde000-017b-11ea-8fd5-279b12bcf6cf.png)
![image](https://user-images.githubusercontent.com/7173984/68429233-b0616700-017b-11ea-9811-e63e4da6fa47.png)

**Comment by xPaw** [comment]
Thanks, changed it.
