### ISSUE TITLE
Filter wishlist to games containing demo

### ISSUE THREAD

**Issue by Samkiud** [SteamDatabase/BrowserExtension#49]
This is one of the features I've been desiring the most out of Enhanced Steam (now Augmented Steam), but the guys there said to implement this, they either have to scrape each wishlist game's store page, or use some sort of database, and it would takes ages to get implemented for Augmented Steam.

They said I would have better luck requesting this feature for the SteamDB extension, since you already have a great database that is perfect for this.

Any chance we can get it?

**Comment by xPaw** [comment]
No plans to add this, you can feature request this to Steam.
