### ISSUE TITLE
Add "Remove from wishlist" button to app page

### ISSUE THREAD

**Issue by taylankasap** [SteamDatabase/BrowserExtension#54]
This is an enhancement request for Steam store pages.

When a game is on wishlist steam shows a button like this. But when clicked it just opens the wishlist page.
![image](https://user-images.githubusercontent.com/4192479/69792138-11a6b400-11d7-11ea-9e1b-be58fe87c386.png)

It would be easier if clicking this simply removed the game from the wishlist, or a new button next to it to remove from wishlist.

I found people suggested same feature on Steam forums, which Valve apparently didn't pay much attention to:
[Remove from Wishlist on Store Page](https://steamcommunity.com/discussions/forum/10/2595630410193943192/)
[Remove From Wishlist](https://steamcommunity.com/discussions/forum/10/541906989389625988/)
[Remove from Wishlist feature](https://steamcommunity.com/discussions/forum/10/492379439690028737/)
[Remove from Wishlist on Store Page](https://steamcommunity.com/discussions/forum/10/846938350912645410/)
(This list keeps going on and on but I'll just stop here)

**Comment by xPaw** [comment]
For what's it worth, augmented steam already does this.

**Comment by xPaw** [comment]
Valve finally shipped this, so no longer needed.
