### ISSUE TITLE
Large wishlist always broken if this extension enabled on Chrome

### ISSUE THREAD

**Issue by kokizzu** [SteamDatabase/BrowserExtension#55]
It causes most ajax request to show code 500 errors like this:

https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=2
https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=4
https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=7
https://store.steampowered.com/wishlist/profiles/76561198089745840/wishlistdata/?p=9

https://youtu.be/XBCoicQAPH0

**Comment by xPaw** [comment]
Not the extensions fault that steam servers are erroring. We certainly don't modify the requests.
