### ISSUE TITLE
Lowest record price and graphs blocks are missing unless Steamdb is visited beforehand

### ISSUE THREAD

**Issue by varricade** [SteamDatabase/BrowserExtension#57]
After I open browser (latest Chrome) and visit Steam, said blocks are missing for every game. But once I visit steamdb manually and get past the 'checking browser' stage, blocks start working normally everywhere. 
I guess it's because of the cloudflare protection on steamdb.info and the fact that extension somehow can't go past it in the background?

**Comment by xPaw** [comment]
Sounds like your provider (possibly vpn) is black listed causing you to get the checking browser.

Can you email your ip and useragent and I'll look in cloudflare. https://steamdb.info/faq/#how-to-contact-you

**Comment by bestpika** [comment]
I got the same issue.
