### ISSUE TITLE
Release Extension on Microsoft Edge Addons catalog

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/BrowserExtension#59]
Hello xPaw,

I have no intention to increase your workload, but I have to make this request: because users in Mainland China cannot directly access Chrome Web Store, many people cannot get the extension.

Since Microsoft Edge is currently based on Chromium, I think the extension will be available without changes.

So could you release extension on Microsoft Edge Addons catalog?

Thanks!

**Comment by xPaw** [comment]
Signing up as a developer is still a convoluted process for that.

Meanwhile you can download the extension as a zip from github and just load that in Chrome.

**Comment by xPaw** [comment]
Try this https://microsoftedge.microsoft.com/addons/detail/hjknpdomhlodgaebegjopkmfafjpbblg

**Comment by wordlesswind** [comment]
Thank you so much, I am using it.

**Comment by StrangePeanut** [comment]
@xPaw It currently appears to be a couple of versions behind. Are you still maintaining it? Cheers!
