### ISSUE TITLE
Show lowest recorded price on wishlist page

### ISSUE THREAD

**Issue by mtucciarone** [SteamDatabase/BrowserExtension#60]
The only reason why I don't use SteamDB full-time is because there's no way for me to see all of my wishlisted games and their lowest recorded prices in one list.  I have to manually update an Excel document with the games I have on my wishlist + their lowest recorded prices that I've fetched from SteamDB.

This would be an extremely powerful feature to have!

Thanks :)

**Comment by mtucciarone** [comment]
Thanks so much @xPaw !! :D

**Comment by xPaw** [comment]
No plans to add this.
