### ISSUE TITLE
Display players online block at google chrome

### ISSUE THREAD

**Issue by gamersfan** [SteamDatabase/BrowserExtension#61]
I did not see players online statistic block, but this option enable at options!
"Add a block on Steam Store displaying online stats (extra http request to steamdb.info)"

I tested at notebook/pc, asked friend to install extension, he didnt see too.

BUT! Sometimes this block is appear! 
Then i serf internet a little, go back to steam game page, refrest it and block disappear again.
I repeat, i tested at many PC, every have the same problem.

"Display last depot update on app pages" didnt work too..
All other function work fine.

I have video, what happened when i refresh the page:
https://youtu.be/c6kYUw2jwlI

This is mystic..

**Comment by xPaw** [comment]
Tet disabling all your extensions, that looks it it's being blocked by adblocker or something.

**Comment by gamersfan** [comment]
But what should i do :c

**Comment by xPaw** [comment]
Send an email to us with this data here: https://steamdb.info/cdn-cgi/trace

I can't promise that it will be fixed though.

**Comment by gamersfan** [comment]
I am new at github, sorry :D
Send on this thread ? Or where ?

fl=73f94
h=steamdb.info
ip=176.36.31.196
ts=1588789589.149
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
colo=WAW
http=http/2
loc=UA
tls=TLSv1.3
sni=plaintext
warp=off

**Comment by gamersfan** [comment]
Send to hi@xpaw.me
