### ISSUE TITLE
How to find the latest depots update with changes to game files?

### ISSUE THREAD

**Issue by 07416** [SteamDatabase/BrowserExtension#65]
While the addon displays this information, the link only leads to `https://steamdb.info/app/*/history/`

An example, the store page tags in particular constantly change for many games:

https://store.steampowered.com/app/20/Team_Fortress_Classic/ 

>Depots Update: 8 October 2019 (225 days ago)

https://steamdb.info/app/20/history/

**Comment by xPaw** [comment]
You can find the depot changes in history if you scroll down, or click through to the depot you want from depots tab.

**Comment by 07416** [comment]
> 
> 
> You can find the depot changes in history if you scroll down, or click through to the depot you want from depots tab.

How the addon determines the last depots update?

Would it be possible to link directly to this depot with changes to game files?

**Comment by xPaw** [comment]
> How the addon determines the last depots update?

Click depots tab, and see public branch, it takes last updated from there.

> Would it be possible to link directly to this depot with changes to game files?

No, as a game has more than 1 depot.
