### ISSUE TITLE
Don't work with Torch (Chromium-based browser)

### ISSUE THREAD

**Issue by diegobh** [SteamDatabase/BrowserExtension#67]
I want to use this to show game statics at steam game store page. I want shows up these informations:

Online now:
Peak today:
All-time peak:
Followers:

But the div (content) don't shows up. It shows very fast at page load but disappears too fast.
Idk the reason.
Rarely it shows up, but its very rare. Almost all the time it just don't works.

if i got to extensions options and i noticed that the pop-up with options don't shows up too and nothing happens after clicked Extension options (it don't shows up the popup)

I tried disable adblock and antivirus to see if some of those are blocking but i got the same result.
It works great on firefox, but i don't use much firefox. My first browser is Torch.

Any fix or workaround, please?

Thank you!!!!

**Comment by xPaw** [comment]
If it works in other browser, but not the browser you are trying, the issue is with said browser.
