### ISSUE TITLE
Remove steamdb.localhost from Chrome Web Store build

### ISSUE THREAD

**Issue by Descear** [SteamDatabase/BrowserExtension#68]
Version 2.6.0. Installed from the Chrome Web Store.

Was this a mistake?

![Screenshot from 2020-07-04 11-19-14](https://user-images.githubusercontent.com/47546329/86510887-df53d980-bdeb-11ea-809b-55ced0f64554.png)

Please delet this.

```js
{
    // [...]
    "version": "2.6.0",
    // [...]
    "permissions": [
        // [...]
        "https://steamdb.localhost/",
        // [...]
    ],
    // [...]
    "content_scripts": [
        {
            "matches": [
                "https://steamdb.localhost/*",
                // [...]
            ],
            // [...]
        },
        // [...]
    ],
    // [...]
}
```

**Comment by xPaw** [comment]
Yes this was a mistake and I could not upload a fixed build because it was stuck in review.

https://twitter.com/thexpaw/status/1279133697183305729

**Comment by Descear** [comment]
> I uploaded 2.6.1 which removes the uninteded permission and it is stuck in review again.

It's gone through now. Thanks.
