### ISSUE TITLE
Add optional link to protondb page on store

### ISSUE THREAD

**Issue by Narcha** [SteamDatabase/BrowserExtension#69]
Since this is basically a must-check before buying a game on Linux, it would be nice to have a link on the game's store page.
For example: on the [store page](https://store.steampowered.com/app/526870/Satisfactory/) there should be a button leading to the game's [protondb page](https://www.protondb.com/app/526870)

**Comment by xPaw** [comment]
No plans for this, sorry. Perhaps ProtonDB can make a userscript themselves to add this.

**Comment by jn64** [comment]
Alternative solution: a simple bookmarklet that swaps `store.steampowered.com` with `www.protondb.com`.
```js
javascript:(function(){var l=location;var h=l.hostname,p=l.pathname,S='store.steampowered.com',P='www.protondb.com';if(h==S){l.assign('https://'+P+p)}else if(h==P){l.assign('https://'+S+p)}})();
```

Click this bookmarklet on `https://store.steampowered.com/app/123/xyz` to load `https://www.protondb.com/app/123/xyz`, or vice versa.

I don't even check if the path starts with `/app`, but obviously it only makes sense to use on such pages. Both sites technically ignore the first path segment after the appid (`/xyz`).

Related #164 #246

---

I use this same type of bookmarklet to swap between `www.reddit.com` and `old.reddit.com`, `amazon.com` and another country, Dotabuff and OpenDota match history, anything else where two sites point to the same identifier with a similar path.
