### ISSUE TITLE
Depots Update + Concurrent Players widget fails to load in Firefox / Waterfox

### ISSUE THREAD

**Issue by RathaWynter** [SteamDatabase/BrowserExtension#75]
When loading the Steam store page for a game, rather frequently the Depots Update info will fail to load. This feature (seems) to be tied to the Concurrent players widget too as when the Depots Update info is missing, Players info fails to load as well. This issue has happened for quite some time in older versions of Firefox (55.03 and 56) but also seems to routinely break in Waterfox Classic 2020.09 though i cannot reliably duplicate the cause of it breaking.

![Area - 2020-10-22 - 02 52 53](https://user-images.githubusercontent.com/35881801/96861410-49d36880-1421-11eb-9a47-69d40a9a151b.png)

Once it breaks it seems to remain broken almost permanently (from weeks to months.) While broken in FF / Waterfox however, it will seem to work just fine in Chrome (I have never known it break in Chrome.) At first I thought this was an API / too many calls / blocking issue, but clearing cookies and logging back in on SteamDB shouldnt fix anything if that were the case.

I have found what seems to be pretty reliable way to fix the problem however:
- Clear all SteamDB related cookies.
- Log into SteamDB using SteamLogin.
- Refresh Steam store page that didnt load Depots Update / Concurrent Players widget. (Should now be fixed)

Tested solutions that didnt work separately:
- Just clearing SteamDB cookies and refreshing page does not fix.
- Just Logging out of SteamDB, logging back in, and refreshing the page does not fix.
- Just clearing Steam cookies does not fix. (Neither does logging back into Steam after clearing cookies)
- Just opening the Store page in a private browsing window does not fix.

Possibly related:
- Occasionally the Homepage link (which seems to be created by the Augmented Steam plugin?) and typically appears to the right of the Depots Update will not show up when the Depots Update is working. Hovering over this link says "As Seen by Steam Database" and has the link: https://steamdb.info/app/231310/history/?utm_source=Steam&utm_medium=Steam&utm_campaign=SteamDB%20Extension which seems strange to me if it does not show up when Augmented Steam is not loaded. (Not sure if this is a conflict between SteamDB 2.8.0 and Augmented Steam 1.4.0. With that said, Depots Update will fail to show even when Augmented Steam addon is not loaded, so the two issues may not be fully related.)

![SteamDB_Homepage_Issue](https://user-images.githubusercontent.com/35881801/96864327-76897f00-1425-11eb-8210-2f29979f8841.png)
)

System Information:
Windows 7 x64
Waterfox Classic 2020.09 (Also Firefox 55.03, 56.0)
SteamDB Plugin version 2.8.0

**Comment by xPaw** [comment]
Sounds like you have some "privacy" flags enabled in Firefox, do you?

**Comment by RathaWynter** [comment]
The only thing i can think of is 'accept third party cookies' set to 'from visited'

![WaterfoxPrivacy](https://user-images.githubusercontent.com/35881801/96866348-6c1cb480-1428-11eb-8d46-f0950075697d.png)

**Comment by xPaw** [comment]
It is probably being blocked by third-party stuff in your browser.

I'm closing this issue because you are using an old browser.

**Comment by xPaw** [comment]
Just for my own curiosity, can you post your waterfox useragent from here: https://steamdb.info/cdn-cgi/trace

**Comment by RathaWynter** [comment]
Waterfox Classic 2020.09
fl=28f248
h=steamdb.info
ip=69.146.140.***
ts=1603367405.039
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.3
colo=SEA
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=off

I do not know the actual codebase that Waterfox Classic uses, though in order to support older plugins that were killed off with the FF57 update, I suspect it needs to report a pre-57 variant for compatibility purposes. Will have to see if i can duplicate this in a standard modern version of FF as well.

The fact that it works sometimes and is fixed by deleting SteamDB cookies *and* logging into SteamDB with Steam login is quite an oddity.

**Comment by xPaw** [comment]
I tweaked a firewall rule, might have helped with Waterfox.

**Comment by RathaWynter** [comment]
Preliminary use of the plugin after that change is leading me to believe that you may have resolved the issue. A simple reload of a tab that didnt load the Depot Update info earlier resulted in it working as expected shortly after you applied the fix and has continued to work for new pages ever since without having to apply the temporary workaround. (It was constantly breaking every ~15-20 minutes previously.)

Wasnt aware that a firewall issue on the website could be a thing, but blocking requests from what appears as an older user agent probably makes the most sense out of anything I could come up with based on the rather odd behavior of the issue. I appreciate you taking the time to make a second look into the problem and come up with firewall rules as a possible cause of the issue. If things break again I will see if I can duplicate the problem in a modern version of the FF client and submit a report on that. (Last Depots Update is a feature i find to be critically useful on the store page.)

(Regarding the use of Waterfox Classic (Last updated Sep 2020), I needed the Pre-57 plugin support that it provides. I made the upgrade from a much older FF a couple of weeks ago in the hopes of having a better supported browser with some modern features and security while retaining legacy plugin support.)

**Comment by danielwerg** [comment]
Had the same issue, changing `privacy.resistFingerprinting` to `false` in `about:config` fixes it.

**Comment by RathaWynter** [comment]
Has there been a regression in this for anyone else? Accidentally updated the plugin last night which caused the Depots Update and Concurrent player list fails to show on the steam store page again. To troubleshoot this i uninstalled and reinstalled previous versions of the plugin till I found one that worked. The last version these features work on is 2.8.6 Released Apr 1, 2021. All the newer versions seem to be broken in Waterfox 2021.04.2.

**Comment by xPaw** [comment]
Is there any actual error information you can provide? Generally speaking Waterfox is using outdated Firefox code, so I don't directly support it.

**Comment by RathaWynter** [comment]
Without knowing specifically where to look for additional debug information, this is about all that I can provide that might be of use:

![2 8 6 - Working](https://user-images.githubusercontent.com/35881801/124389481-893aa000-dca4-11eb-97d6-48016fd3e27f.png)

![2 8 7 - Broken](https://user-images.githubusercontent.com/35881801/124389488-9061ae00-dca4-11eb-85cb-7933813d18b9.png)

**Comment by xPaw** [comment]
I just installed Waterfox in sandbox and latest addon version (v2.9.4) and it works just fine.

**Comment by RathaWynter** [comment]
I misspoke earlier when i said Waterfox, I meant Waterfox Classic 2021.04.2. (I will update to newest classic and test again, thought it was already latest.)

**Comment by xPaw** [comment]
I'm not gonna support Waterfox Classic.

**Comment by RathaWynter** [comment]
Re-tested with Waterfox Classic 2021.06 with SteamDB 2.9.4 and still broken.

https://github.com/SteamDatabase/BrowserExtension/issues/75#issuecomment-714449030
Last time there was an issue you mentioned changing a firewall rule, Though that was a problem that seemed to be broken intra-version and not by a version upgrade. Bit strange that the problem exhibits the exact same behavior as before though.

**Comment by RathaWynter** [comment]
For what its worth, these are the two commits between versions 2.8.6 and 2.8.7 where it stops working:

Add StoreAddFreeLicense
https://github.com/SteamDatabase/BrowserExtension/commit/c6bb4ed21c9571162c61cad9583c1e93172043c5

Add appid to playtest banner 
https://github.com/SteamDatabase/BrowserExtension/commit/050cd58aad04d1eedc9ceea0500891a6584489b4
