### ISSUE TITLE
Browser Extension not detected by SteamDB

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#78]
I'm using Brave browser, which is a chromium browser. It's pretty much google chrome and it supports all its extensions. Well, not yours it seems like. I'd love it if you could look into it!

**Comment by Revadike** [comment]
![image](https://user-images.githubusercontent.com/4411977/107892025-a0116d80-6f22-11eb-9a43-c1393f8e052a.png)

**Comment by xPaw** [comment]
Not detected where exactly?

**Comment by Revadike** [comment]
https://steamdb.info/bundles/

**Comment by Revadike** [comment]
Nevermind, I'm stupid. I read your message wrong. I thought because it said I require the extension for these filters, that it was not detected.
