### ISSUE TITLE
[feature request] an option to set all Steam forum threads to display 50 messages by default (or more)

### ISSUE THREAD

**Issue by 07416** [SteamDatabase/BrowserExtension#79]
a lengthy example thread: https://steamcommunity.com/app/570/discussions/0/1629663905431002097/

`javascript:Forum_SetTopicRepliesPerPage( 50 );`

I feel that the value frequently reverts back to 15. 50 is the highest officially supported value to my knowledge and many would likely always use 100 or so if possible.

**Comment by xPaw** [comment]
I think they set a cookie per thread, so that's pretty silly.

Anyway, this is more of a request for Valve, not for this extension.
