### ISSUE TITLE
[Feature Request] Option to Set Default Displayed Currency on SteamDB

### ISSUE THREAD

**Issue by aaronhatesregex** [SteamDatabase/BrowserExtension#80]
## Feature Description

Add a setting to set the shown currency on SteamDB website **regardless of the cookie or IP or whatever**.

## User Case

Now it's possible to append param like `?cc=jp` to the url of Steam or SteamDB (manually or automatically through a third-party extension) to achieve that, but it would be great if the extention supports that.

## Further Information

Though there is closed issue #28 on the setting of displayed currency, I open a new issue since (I assume) the user case is different.

**Comment by xPaw** [comment]
Why? And why is this request in the extension?

**Comment by aaronhatesregex** [comment]
Uh, I can think up three kinds of situation that would need this feature.

1. I am travelling in another country which uses a different currency and want to see the price in the currency in my country (and perhaps I don't want to login in).
2. Some games are not available in my region but are cross-region-giftable. If I happen to have a friend in that place, I can ask the person to gift it for me and roughly see how much I'll pay.
3. To speak it less explicitly, one wants to do something that's against [Steam Subscriber Agreement Section 3 Clause A](https://store.steampowered.com/subscriber_agreement/#3) (mostly the last paragraph).

For the second question, as the target currency is already shown after login (hence no need for such option), if this feature gets added, I think the extension is the right place.

**Comment by xPaw** [comment]
SteamDB sets a cookie with the currency you select, so your browser will remember your cc on steamdb.info. The extension will show the same currency as the page itself for the lowest price.

For Steam, cc parameter does not work if you are logged in.
