### ISSUE TITLE
Free packages rate limiter

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#82]
The addition of the `Activate these packages now` button is cool and very convenient.
However, I think it's fair to assume most people don't keep up, resulting in having over 50 packages to redeem.
To make it even more convenient, allow people to keep their page open for the redeeming process to keep going while adhering to the rate limit. 
So, redeem until you're rate limited, wait 1h and continue redeeming the rest of the packages in this fashion.
You could even make this feature optional if you want with a checkbox, or a stop button, but I think it ain't needed as people can just leave the page.
This feature should be really easy to add and will cost no additional resources for SteamDB. 
People will still need to manually refresh the page to retrieve an updated filtered list.

**Comment by xPaw** [comment]
Maybe.

**Comment by Revadike** [comment]
While we're on the subject. The rate limits are the same as for activating steam keys.
Which is: 50 successful activations until cooldown, and 10 failed attempts until cooldown.
Though, seems like `This product is already available in your Steam library.` is counted as failed, yet `There was a problem adding this product to your account.` is not counted as failed.
The cooldown works as follows: it's a predicate that check your activations from the past 1 hour for the criteria as described above.

**Comment by Revadike** [comment]
https://github.com/DoctorMcKay/node-steam-user/blob/master/enums/EPurchaseResultDetail.js
