### ISSUE TITLE
Lowest recorded price box has incorrect value for now-free games

### ISSUE THREAD

**Issue by Nixinova** [SteamDatabase/BrowserExtension#83]
See [CSGO](https://store.steampowered.com/app/730/CounterStrike_Global_Offensive/) for example. The game is now free yet SteamDB states the lowest price is $9. The box should either disappear or state that the lowest price is $0.

![image](https://user-images.githubusercontent.com/42429413/116160030-62606a80-a745-11eb-9552-9e7e16b8f9fd.png)

**Comment by Nixinova** [comment]
`GetPrice` doesn't return the current value so there's nothing to test the "lowest" against.
(Also "price" should really be split into "currency`str`" and "price`num`".)

![image](https://user-images.githubusercontent.com/42429413/116161220-7dcc7500-a747-11eb-943b-dda53e6e07db.png)

https://github.com/SteamDatabase/BrowserExtension/blob/050cd58aad04d1eedc9ceea0500891a6584489b4/scripts/store/app.js#L79-L84

**Comment by Nixinova** [comment]
Well, Steam's API does seem to be a bit confusing around this.

The package details don't mention the new price:
```js
fetch('https://store.steampowered.com/api/packagedetails?packageids=730')
  .then(r => r.json())
  .then(d => console.log(d[730].data.price))
// {"currency":"NZD","initial":1669,"final":1669,"discount_percent":0,"individual":0}
```

But the app details does have a `is_free` param:
```js
fetch('https://store.steampowered.com/api/appdetails?appids=730')
  .then(r => r.json())
  .then(d => console.log(d[730].data.is_free))
// true
```

**Comment by Nixinova** [comment]
> GetPrice doesn't return the current value so there's nothing to test the "lowest" against.

Should I open an issue at https://github.com/SteamDatabase/SteamDatabase to request adding more output data to `https://steamdb.info/api/ExtensionGetPrice/`?

**Comment by xPaw** [comment]
That endpoint will no longer return data if game is currently free on the store.
