### ISSUE TITLE
Option to automatically hide free packages

### ISSUE THREAD

**Issue by Faalagorn** [SteamDatabase/BrowserExtension#84]
Especially since https://github.com/SteamDatabase/BrowserExtension/issues/82#issuecomment-818011690 seems to have been added, could there be an added option (ideally with the ability to turn on/off, maybe even with selectable error messages) to automatically hide all the failed attempts, so they don't use up limits?
![Screenshot from 2021-05-11 10-25-49](https://user-images.githubusercontent.com/4951331/117784789-34e6e700-b244-11eb-92b1-15e8e33c607b.png)

**Comment by xPaw** [comment]
Don't use no_filters if you don't want to hit all the errors.
