### ISSUE TITLE
Support the safari browser

### ISSUE THREAD

**Issue by iMonZ** [SteamDatabase/BrowserExtension#85]
I would like to add the support for the safari browser.
Is this an emotional thing that you don’t want it or has this a technical reason?

**Comment by xPaw** [comment]
I have plenty of technical problems with Apple and how they do things. I am not going to sign up for the app store and publish the addon there, even if it is technically easy to port the code to work on it.

**Comment by iMonZ** [comment]
> I have plenty of technical problems with Apple and how they do things. I am not going to sign up for the app store and publish the addon there, even if it is technically easy to port the code to work on it.

But you don’t have to sign up anywhere.
Why do you need that?

**Comment by xPaw** [comment]
Because I am not going to let a user I have never seen before publish it for me.

**Comment by iMonZ** [comment]
> Because I am not going to let a user I have never seen before publish it for me.

I’m not going to publish anything.
commiting code -> Pull request.
Compiling
People download the binary thats it

there is no publishing involved

**Comment by xPaw** [comment]
And how many people are actually going to through the trouble of installing it manually, and not from the app store?

I will not be able to test or fix things for Safari.

**Comment by iMonZ** [comment]
> And how many people are actually going to through the trouble of installing it manually, and not from the app store?
> 
> I will not be able to test or fix things for Safari.

Since safari support Firefox and chrome extension this is pretty easy 
I can also do a fork but then I need the agreement of the project owner

**Comment by iMonZ** [comment]
> And how many people are actually going to through the trouble of installing it manually, and not from the app store? This also has no auto updating.
> 
> I will not be able to test or fix things for Safari.

Which trouble?
Double tab on the .app file that’s inside an zip file or dmg and it’s done (you need to check the tick in the extension settings)

**Comment by xPaw** [comment]
Look, I don't want to keep arguing about this. I don't care about Safari nor do I want to support it.

**Comment by iMonZ** [comment]
> Look, I don't want to keep arguing about this. I don't care about Safari nor do I want to support it.

Thanks for the discussion.
I feel again like I’m talking to a wall with some Apple haters.
But well it’s not my problem but I love to see how developers doing everything in there power to limit there projects👍🏻
great work

**Comment by xPaw** [comment]
To properly support the addon, I would have be able to test and use it myself. I have seen plenty of times when people come to a project, offer to add a new feature and then promptly disappear leaving the maintenance burden on the project maintainers.

If you think that people will go out of their way to manually install addons, you are solely mistaken. On top of that, percentage of Safari users is low enough to not warrant doing this.
