### ISSUE TITLE
Extension not Loading GetPrice failed to load: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by TylerJaacks** [SteamDatabase/BrowserExtension#86]
When I load a Steam page I see the player count for the game box show up for a second and disappear and none of the features appear.

Chrome 91.0.4472.77  Console Log

[SteamDB] Matched country as "us" from search script and currency as "USD"
common.js:80 [SteamDB] GetPrice failed to load: Unexpected token < in JSON at position 0
common.js:80 [SteamDB] GetCurrentPlayers failed to load: Unexpected token < in JSON at position 0

**Comment by xPaw** [comment]
That's likely Cloudflare firewall, which I think fixed.

If you still hit this, please grab https://steamdb.info/cdn-cgi/trace and send us an email.

**Comment by TylerJaacks** [comment]
What is your email?

**Comment by xPaw** [comment]
https://steamdb.info/faq/#how-to-contact-you
