### ISSUE TITLE
Add relative date to historical lowest price display

### ISSUE THREAD

**Issue by qs-arno** [SteamDatabase/BrowserExtension#87]
Currently, the historical lowest price notification looks like this:

![steamdb-historical-lowest-price-before](https://user-images.githubusercontent.com/12985596/120025843-e2812680-bfb6-11eb-9ee7-9d23f3757af1.png)

It would be nice if it included the date of SteamDB's first recorded price, like so:

![steamdb-historical-lowest-price-after](https://user-images.githubusercontent.com/12985596/120025840-e1e89000-bfb6-11eb-8c9c-88a04d45431b.png)

The way I like to do "fuzzy durations" is to pick the largest single unit in the duration (in this case, years), and just report that with a decimal value (such as what's in the "after" example).  As opposed to something like "3 years, 6 months, 2 weeks, and 5 days" etc. which is only slightly more precise but _much_ more wordy.  That said, I don't really care about the formatting/precision as long as I can get a reasonable ballpark value.

**Comment by qs-arno** [comment]
The reasoning behind having this extra information to assist with differentiating betweeen:

1. The item is on sale for x% but it's only been out for a month and it's not reeeally my cup of tea, so I can toss it back in the pond and see if it goes on sale for x+y% later, and
2. The item is on sale for x%, and x% is the lowest it's ever been for a year.  This is realistically the best it's gonna get unless I want to try waiting a _really_ long time.

...or...

1. The item is on sale for x%, has been tracked for three years, and the first instance of x% is from two months after release.  At this point, it's pretty clear the publisher has decided on a lower boundary, and
2. The item is on sale for x%, has been tracked for three years, and the first instance of x% is yesterday.  Clearly the publisher is reevaluating their pricing strategy.

I mean, at the end of the day, the ideal scenario would be to just have the entire price history graph embedded right there, but I assume that's impractical or it'd already be there.  🙂

**Comment by xPaw** [comment]
Looks like you put two separate ideas into this issue, which makes it confusing.

1. You want relative dates
2. You want to see when the game went on sale (aka the release date?)

**Comment by xPaw** [comment]
To be honest your suggested example reads very confusingly, and there's limited value in that as far as I can see.

(Side note, I do have to tweak the text/styling of the banner after adding last seen dates).

**Comment by qs-arno** [comment]
If you think the wording is confusing, maybe just take the duration out since it's redundant data-wise anyway?

```
SteamDB lowest recorded price since Nov 9, 2017 (3.5 years ago) is $0.59 at -80% on 25 Jun 2020 (2 times, first on 20 Mar 2019)
```

...becomes:

```
SteamDB lowest recorded price since Nov 9, 2017 is $0.59 at -80% on 25 Jun 2020 (2 times, first on 20 Mar 2019)
```

That way all you're adding is `since Nov 9, 2017`.

**Comment by xPaw** [comment]
That's still very overloaded. Besides, what advantage does this have since you can see release date on the page already?

**Comment by qs-arno** [comment]
Yeah, that's true.  I mean, I guess there's a potential discrepancy between the actual Steam release date and SteamDB's first sampling of the price, but in practical terms I imagine it's very rare that there's any meaningful difference between the two.

**Comment by xPaw** [comment]
You'd be right to assume that, and games older than SteamDB have mostly gone on sale by now for us to record a lower discount.
