### ISSUE TITLE
The "lowest recorded price" cannot be displayed

### ISSUE THREAD

**Issue by bestpika** [SteamDatabase/BrowserExtension#90]
Since the beginning of this sale, this extension does not show the lowest recorded price.
![image](https://user-images.githubusercontent.com/5698157/122732703-1f3af780-d2af-11eb-81e3-9ca76e42d517.png)
I saw some information in the console.
![image](https://user-images.githubusercontent.com/5698157/122734359-9624c000-d2b0-11eb-8700-d661e03e608e.png)

**Comment by xPaw** [comment]
What browser and version is that?

**Comment by bestpika** [comment]
@xPaw
CentBrowser 4.3.9.248
SteamDB Extension 2.9.4

I suspect that I encountered the wall of Cloudflare, but I tried to access SteamDB first and still couldn't get the information properly.

**Comment by xPaw** [comment]
Cloudflare was triggering on old Chrome version, should work now.
