### ISSUE TITLE
Easy options toggle

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#91]
Add the ability to easily toggle all options on and off.
Similarly, an easy toggle for steamdb.info-only features and steam-only features.
Why? For lazy and simple-minded people like me.

**Comment by xPaw** [comment]
You might as well disable the extension entirely if you want to toggle all options. Your browser has that option.

![image](https://user-images.githubusercontent.com/613331/122876233-f0b82d80-d33d-11eb-8a88-17acdb28e7d3.png)

**Comment by Revadike** [comment]
Yes, you're right, but I was thinking it could be handy as a use case to disable all options with 1-click and then go through enabling one by one which option you like.
Also, you ignored the steamdb.info-only and steam-only toggle, which for me is the most interesting feature. For Steam I already use Augmented Steam, so I prefer to just have the steamdb.info features enabled.
Additionally, you could have an option to reset options to default.
