### ISSUE TITLE
Parse licenses

### ISSUE THREAD

**Issue by Revadike** [SteamDatabase/BrowserExtension#94]
Parse the [licenses page](https://store.steampowered.com/account/licenses) just like userdata is being used.
This allows you to do all kinds of fun stuff.
Some ideas:

 * Show license acquire date on /sub SteamDB pages (and steam store pages)
 * Show what games you got during each sale history
 * Show stats, like the ones possible from your [license parser](https://lab.xpaw.me/license-parser.html)
 * Likewise, show account value over time in /calculator
 * Cross-reference owned packages and licenses, to submit package name suggestions to SteamDB (encrypted?) for unknown packages, and if enough people submit it, you can display it as an unconfirmed name? 
 * Have a purchase date column in your games tables on the /calculator page

How to cross-reference license and package:
 1. If known to SteamDB or packagedetails API, simply match license name with SteamDB/packagedetails package name.
 2. If unknown to SteamDB or packagedetails API:
    1. Get list of owned apps.
    2. Exclude apps from packages that are known to SteamDB.
    3. For each unknown app, request:
    ```
    https://help.steampowered.com/en/wizard/HelpWithGameIssue/?appid=APPID&issueid=123&sessionid=SESSIONID&wizard_ajax=1
    ```
    4. Find the license/package name, appid and subid in the response

**Comment by xPaw** [comment]
License page has no subids. As for stats I think AS does that already?

**Comment by Revadike** [comment]
> License page has no subids. As for stats I think AS does that already?

I don't use AS.
Also I solved the problem for no subids in license page, please read...

**Comment by xPaw** [comment]
I'm not going to spam the help site with requests to figure out which package is which.

**Comment by Revadike** [comment]
> I'm not going to spam the help site with requests to figure out which package is which.

I should only be a small portion of the licenses, I reckon.
Besides, you haven't shy away from spamming steam before, just look at the free packages script for example.
