### ISSUE TITLE
Add support for firefox mobile

### ISSUE THREAD

**Issue by james2432** [SteamDatabase/BrowserExtension#97]
Currently we cannot install this on firefox for android as the extension only works with desktop firefox(from the mozilla extension page)

**Comment by xPaw** [comment]
You can't install it on Android because Mozilla whitelists only like 20 extensions you can install, there's nothing I can do about it.

**Comment by clst** [comment]
FYI: It's a bit of a chore but you can install all extension on FF nightly:

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
